name: aemail
description: AE Mail App
version: 0.2.0+200
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  aeuniverse:
    path: ../aeuniverse
    
  core:
    path: ../core

  core_ui:
    path: ../core_ui

  flutter:
    sdk: flutter

  # handle SVGs for Android, iOS, and Web.
  websafe_svg: ^2.1.1

  # which supports multiple columns with rows of varying sizes
  flutter_staggered_grid_view: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/Icons/
    - assets/images/