name: uniris_mobile_wallet
description: Uniris Wallet app (iOS/Android).

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.10+10

environment:
  sdk: '>=2.12.0 <3.0.0'
    
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # Securley store data in a keystore
  flutter_secure_storage: ^4.2.0

  # Shared prefs
  shared_preferences: ^2.0.6

  # Flare for animations
  flare_flutter: ^3.0.0

  # Platform-specific build info
  package_info: ^2.0.1

  # Device-specific info
  device_info: ^2.0.1

  # JSON Serialization
  json_annotation: ^3.1.1

  # Localization
  intl: ^0.17.0 

  # BigDecimal alternative
  decimal: ^1.1.0

  # SQLite
  sqflite: ^2.0.0+3

  # Android/iOS path provider
  path_provider: ^2.0.2
  
  # TouchID/FaceID
  local_auth: ^1.1.5
 
  # Eventbus
  event_taxi: ^1.0.0

  # SVG
  flutter_svg: ^0.22.0

  # QR Codes
  qr_flutter: ^4.0.0

  # Generator
  barcode_scan2: ^4.1.3
  
  # HTTP client
  http: ^0.13.3

  pointycastle: ^3.0.1
  
  # Vibrate
  vibration: ^1.7.4-nullsafety.0
  
  # Toast
  oktoast: ^3.0.0

  # Slidable list actions
  flutter_slidable: ^0.6.0

  # Service provider
  get_it: ^7.1.3
  
  quiver: ^3.0.1

  convert: ^3.0.0

  # Root/Jailbreak detection
  root_checker:
    git:
      url: https://github.com/redDwarf03/root_checker.git
      ref: master

  # Validation utilities
  validators: ^3.0.0

  # Auto resize text widget
  auto_size_text: ^3.0.0-nullsafety.0

  flip_card: ^0.5.0

  # Avoid keyboard from overlapping text fields
  keyboard_avoider: 
    git:
      url: https://github.com/redDwarf03/keyboard_avoider.git
      ref: master

  uniris_lib_dart:
    git:
      url: https://github.com/redDwarf03/uniris_lib_dart.git
      ref: master
    
  fluttericon: ^2.0.0

  fl_chart: ^0.36.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.11.1
  json_serializable: ^3.5.1
  import_sorter: ^4.6.0
  intl_translation:
    git: 
      url: https://github.com/reddwarf03/intl_translation.git
      ref: master 

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

flutter_icons:
  android: true
  ios: true
  image_path: "assets/uniris_icon.png"

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
          weight: 500
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
  assets:
    - assets/QR.svg
    - assets/uniris_icon.png
    - assets/uniris_logo.svg
    - assets/send_animation.flr
    - assets/searchseedqr_animation_magnifyingglassonly.flr
    - assets/searchseedqr_animation_glassonly.flr
    - assets/searchseedqr_animation_qronly.flr
    - assets/searchseedmanual_animation_magnifyingglassonly.flr
    - assets/searchseedmanual_animation_glassonly.flr
    - assets/searchseedmanual_animation_seedonly.flr
    - assets/pulltosend_animation.flr
    - assets/sheethandle_animation.flr
    

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  