name: archethic_mobile_wallet
description: ARCHEthic Wallet app (iOS/Android).

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.27+27

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # ArchEthic dart library for Flutter based on Official ArchEthic Javascript library for Node and Browser
  archethic_lib_dart:
    git:
      url: https://github.com/archethic-foundation/libdart.git
      ref: master

  # Flutter widget that automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^3.0.0

  # A flutter plugin for scanning 2D barcodes and QRCodes via camera
  barcode_scan2: ^4.1.4

  # Dart implementation of Bitcoin BIP39 Mnemonic code for generating deterministic keys
  bip39: ^1.0.6

  # Utilities for converting between data representations. Provides a number of Sink, Codec, Decoder, and Encoder types
  convert: ^3.0.1

  # The decimal package allows you to deal with decimal numbers without losing precision
  decimal: ^1.3.0

  # EventTaxi could be used to send events through different layers of the application decoupled from the architecture
  event_taxi: ^1.0.0

  # A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart
  fl_chart: ^0.40.2

  # A component that provides flip card animation. It could be used for hide and show details of a product
  flip_card: ^0.5.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android
  flutter_secure_storage: ^5.0.0-beta.5

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files
  flutter_svg: ^0.23.0+1

  # A Flutter plugin to vibrate the device
  flutter_vibrate: ^1.3.0

  # The Font Awesome Icon pack available as set of Flutter Icons.
  font_awesome_flutter: ^9.1.0

  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App
  get_it: ^7.2.0

  # Hive is a lightweight and blazing fast key-value database written in pure Dart
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # A composable, multi-platform, Future-based API for HTTP requests
  http: ^0.13.4

  # Lazily load and display pages of items as the user scrolls down your screen.
  infinite_scroll_pagination: ^3.1.0

  # Localization
  intl: ^0.17.0

  # Flutter plugin for Android and iOS devices to allow local authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern
  local_auth: ^1.1.8

  # A pure flutter toast library Support custom style/widget. Easy to use. You can use this library to achieve the same effect as Android toast
  oktoast: ^3.1.4

  # Flutter plugin for querying information about the application package, such as CFBundleVersion on iOS or versionCode on Android
  package_info_plus: ^1.3.0

  # QR.Flutter is a Flutter library for simple and fast QR code rendering via a Widget or custom painter
  qr_flutter: ^4.0.0

  # Quiver is a set of utility libraries for Dart that makes using many Dart libraries easier and more convenient, or adds additional functionality
  quiver: ^3.0.1+1

  # With the Flutter safe_device package, you can easily implement security steps such as Jailbroken, root, emulator and fake location detection.
  safe_device: ^1.0.9

  # Flutter plugin for reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS and SharedPreferences on Android
  shared_preferences: ^2.0.8

  # String validation and sanitization for Dart
  validators: ^3.0.0

  # A Flutter plugin that provides a WebView widget
  webview_flutter: ^2.1.2
 
dev_dependencies:
  # A build system for Dart code generation and modular compilation
  hive_generator: ^1.1.1
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl_generator: ^0.2.1
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/uniris_icon.png"

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: fonts/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/Montserrat-Italic.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
  assets:
    - assets/archethic_logo.svg
    - assets/archethic_logo_alone.svg
    - assets/icons/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true